Repository WGL-2024/WGL_repo_2024, pull requests merged in 2024-12, with the labels that each got.

#102 sync with latest approved changes
  AP-protocol.md
  crates/wg_packet/src/lib.rs
  crates/wg_packet/src/message.rs
  examples/config/config.toml
  examples/config/parser.rs
Labels: ready for merge

#87 Specify minimum connections of clients and drones
  AP-protocol.md
Labels: ready for merge

#100 Add PartialEq
  Cargo.toml
  crates/wg_controller/Cargo.toml
  crates/wg_controller/src/command.rs
  crates/wg_internal/Cargo.toml
  crates/wg_network/Cargo.toml
  crates/wg_network/src/routing.rs
  crates/wg_packet/Cargo.toml
  crates/wg_packet/src/flood.rs
  crates/wg_packet/src/packet.rs
Labels: voted

#106 Data size in Fragment
  AP-protocol.md
  crates/wg_packet/src/packet.rs
Labels: change needed

#81 Remove DroneOptions in new()
  crates/wg_drone/src/drone.rs
  examples/drone/drone_usage.rs
Labels: change needed

#114 Managing Drone crash (union of PR #108 and #109)
  AP-protocol.md
  crates/wg_controller/src/command.rs
Labels: please review so I can merge it

#113 Clarification of SC - Nodes commands
  AP-protocol.md
  crates/wg_controller/src/command.rs
  crates/wg_drone/src/drone.rs
  examples/drone/drone_usage.rs
Labels: vote on next WG

#89 QOL improvements
  Cargo.toml
  crates/wg_network/src/routing.rs
  crates/wg_packet/src/flood.rs
  crates/wg_packet/src/packet.rs
  examples/qol_improvements/qol_improvements.rs
Labels: change needed
