Repository WGL-2024/WGL_repo_2024, pull requests merged in 2024-11, with the labels that each got.

#15 Adding basic starting action
  .github/workflows/rust-actions.yaml
Labels: ⚙️git, priority

#14 Adding naming conventions
  CONTRIBUTE.md
  README.md
Labels: other

#12 Simplify Message and Packets (+ adding NodeId)
  AP-protocol.md
  src/main.rs
  src/types/message.rs
  src/types/mod.rs
  src/types/packet.rs
Labels: vote on next WG

#5 Proposal section "Source routing"
  AP-protocol.md
Labels: vote on next WG

#17 Adding basic API and Topology
  src/api/drone.rs
  src/api/mod.rs
  src/api/simulation_controller.rs
  src/main.rs
  src/types/message.rs
  src/types/mod.rs
  src/types/topology/mod.rs
  src/types/topology/routes.rs
Labels: vote on next WG

#13 Minor refactoring of serialization
  AP-protocol.md
Labels: ready for merge, refactoring

#29 TTL update
  AP-protocol.md
Labels: ready for merge

#31 Refactoring various files
  src/api/simulation_controller.rs
  src/types/message.rs
  src/types/mod.rs
  src/types/packet.rs
  src/types/source_routing_header.rs
  src/types/topology/mod.rs
  src/types/topology/nodes.rs
  src/types/topology/routes.rs
Labels: ready for merge

#23 Unify the ServerType
  AP-protocol.md
  src/types/message.rs
  src/types/mod.rs
  src/types/topology/nodes.rs
Labels: ready for merge

#36 DroneAPI
  Cargo.toml
  examples/drone_usage_example.rs
  src/api/drone.rs
  src/api/mod.rs
  src/types/command.rs
  src/types/mod.rs
Labels: vote on next WG

#33 Updating packets (adding query and removing fragment data)
  AP-protocol.md
Labels: vote on next WG

#37 Adding registration for Client to Chat
  AP-protocol.md
  src/types/message.rs
Labels: ready for merge

#40 From executable to library
  AP-protocol.md
  Cargo.toml
  assets/costellation.png
  crates/config/Cargo.toml
  crates/config/src/config.rs
  crates/config/src/lib.rs
  crates/controller/Cargo.toml
  crates/controller/src/command.rs
  crates/controller/src/controller.rs
  crates/controller/src/lib.rs
  crates/drone/Cargo.toml
  crates/drone/src/drone.rs
  crates/drone/src/lib.rs
  crates/internal/Cargo.toml
  crates/internal/src/lib.rs
  crates/network/Cargo.toml
  crates/network/src/lib.rs
  crates/network/src/routing.rs
  crates/network/src/topology/mod.rs
  crates/network/src/topology/node.rs
  crates/network/src/topology/route.rs
  crates/packet/Cargo.toml
  crates/packet/src/lib.rs
  crates/packet/src/message.rs
  crates/packet/src/packet.rs
  examples/config/parser.rs
  examples/drone/drone_usage.rs
  examples/drone_usage_example.rs
  examples/parser.rs
  src/api/drone.rs
  src/api/mod.rs
  src/lib.rs
  src/main.rs
  src/types/mod.rs
  src/types/packet.rs
  src/types/topology/mod.rs
  src/types/topology/routes.rs
Labels: ready for merge

#56 wg_config now uses NodeId, pdr f32 like in drone
  crates/wg_config/Cargo.toml
  crates/wg_config/src/config.rs
Labels: ready for merge, minor fix

#54 Add query and query result to packet types (+use NodeId)
  AP-protocol.md
  crates/wg_packet/src/flood.rs
  crates/wg_packet/src/lib.rs
  crates/wg_packet/src/packet.rs
  examples/drone/drone_usage.rs
Labels: please review so I can merge it

#51 Adding derive Clone and Debug to all struct
  crates/wg_config/src/config.rs
  crates/wg_controller/src/command.rs
  crates/wg_drone/src/drone.rs
  crates/wg_network/src/routing.rs
  crates/wg_network/src/topology/node.rs
  crates/wg_network/src/topology/route.rs
  crates/wg_packet/src/flood.rs
  crates/wg_packet/src/message.rs
  crates/wg_packet/src/packet.rs
Labels: please review so I can merge it

#52 Small protocol refactoring
  AP-protocol.md
  crates/wg_packet/src/flood.rs
  crates/wg_packet/src/packet.rs
  examples/drone/drone_usage.rs
Labels: ready for merge

#48 PDR
  AP-protocol.md
Labels: vote on telegram

#68 Removed ambiguity in Fragment Reassembly
  AP-protocol.md
Labels: ready for merge, not to vote

#70 removed time::Instant
  AP-protocol.md
  crates/wg_packet/src/packet.rs
Labels: vote on telegram

#57 added packet_send channels in drone new() function
  crates/wg_drone/src/drone.rs
  examples/drone/drone_usage.rs
Labels: ready for merge

#60 Flood: remove TTL and SourceRoutingHeader
  AP-protocol.md
  crates/wg_packet/src/flood.rs
Labels: ready for merge

#90 Nack errors
  crates/wg_packet/src/packet.rs
Labels: ready for merge, minor fix

#79 Simulation Controller commands specification 2
  AP-protocol.md
  Cargo.toml
  crates/wg_controller/src/command.rs
  crates/wg_controller/src/lib.rs
  crates/wg_drone/src/drone.rs
  examples/drone/config.toml
  examples/drone/drone_usage.rs
Labels: not ready

#92 Removing SimulationController trait
  crates/wg_controller/src/controller.rs
Labels: ready for merge

#96 Restore fragment_id
  crates/wg_packet/src/packet.rs
Labels: vote on telegram

#86 Specify drone implementation
  AP-protocol.md
Labels: vote on telegram

#85 Added priority for simulation controller messages
  AP-protocol.md
  examples/drone/drone_usage.rs
Labels: vote on telegram
